### PR TITLE
Bump version to 0.2.0

### PR DESCRIPTION
**Pull request by kmsquire**
... so a release can be made. 😄 

(See also: https://white.ucc.asn.au/2019/09/28/Continuous-Delivery-For-Julia-Packages.html)

### CODE REVIEW

**Comment by xiaodaigh** [comment]
Thanks! @kmsquire was too busy to update this. Now it's done.

**Comment by kmsquire** [comment]
Thanks!  It would be great if you could also make a release at some point. Cheers!

**Comment by xiaodaigh** [comment]
Already done

**Comment by kmsquire** [comment]
Awesome, thank you!

**Pull request merged**
